-- Kenya Diaspora Missions — Unified Seed (v2)
-- 20260322 — Adjusted for latitude/longitude column names

-- 1. CLEANUP (STRICT MODE)
TRUNCATE public.diaspora_registration_centres CASCADE;

-- 2. SEED DATA
INSERT INTO public.diaspora_registration_centres
(id, mission_name, mission_type, city, country, country_code, continent, region, latitude, longitude, address, designated_2017, designated_2022, designation_count, designation_state, is_iebc_confirmed_2027)
VALUES
  ('ke-ug-kampala', 'Kenya High Commission Kampala', 'high_commission', 'Kampala', 'Uganda', 'UG', 'Africa', 'East Africa', 0.3136, 32.5811, 'Plot 60, Kira Road, Kampala', true, true, 2, 'embassy_probable'::diaspora_centre_state, false),
  ('ke-tz-dar', 'Kenya High Commission Dar es Salaam', 'high_commission', 'Dar es Salaam', 'Tanzania', 'TZ', 'Africa', 'East Africa', -6.7924, 39.2083, 'NIC Investment House, Samora Avenue, Dar es Salaam', true, true, 2, 'embassy_probable'::diaspora_centre_state, false),
  ('ke-tz-arusha', 'Kenya Consulate Arusha', 'consulate', 'Arusha', 'Tanzania', 'TZ', 'Africa', 'East Africa', -3.3731, 36.6941, 'Arusha, Tanzania', true, true, 2, 'embassy_probable'::diaspora_centre_state, false),
  ('ke-rw-kigali', 'Kenya Embassy Kigali', 'embassy', 'Kigali', 'Rwanda', 'RW', 'Africa', 'East Africa', -1.9441, 30.0619, 'Kacyiru, Kigali, Rwanda', true, true, 2, 'embassy_probable'::diaspora_centre_state, false),
  ('ke-bi-bujumbura', 'Kenya Embassy Bujumbura', 'embassy', 'Bujumbura', 'Burundi', 'BI', 'Africa', 'East Africa', -3.3614, 29.3599, 'Bujumbura, Burundi', true, true, 2, 'embassy_probable'::diaspora_centre_state, false),
  ('ke-za-pretoria', 'Kenya High Commission Pretoria', 'high_commission', 'Pretoria', 'South Africa', 'ZA', 'Africa', 'Southern Africa', -25.746, 28.2293, '302 Brooks Street, Menlo Park, Pretoria', true, true, 2, 'embassy_probable'::diaspora_centre_state, false),
  ('ke-ss-juba', 'Kenya Embassy Juba', 'embassy', 'Juba', 'South Sudan', 'SS', 'Africa', 'East Africa', 4.8594, 31.5713, 'Juba, South Sudan', false, true, 1, 'embassy_only'::diaspora_centre_state, false),
  ('ke-et-addis', 'Kenya Embassy Addis Ababa', 'embassy', 'Addis Ababa', 'Ethiopia', 'ET', 'Africa', 'East Africa', 9.0109, 38.7613, 'Addis Ababa, Ethiopia', false, false, 0, 'embassy_only'::diaspora_centre_state, false),
  ('ke-ng-abuja', 'Kenya High Commission Abuja', 'high_commission', 'Abuja', 'Nigeria', 'NG', 'Africa', 'West Africa', 9.0579, 7.4951, 'Abuja, Nigeria', false, false, 0, 'embassy_only'::diaspora_centre_state, false),
  ('ke-eg-cairo', 'Kenya Embassy Cairo', 'embassy', 'Cairo', 'Egypt', 'EG', 'Africa', 'North Africa', 30.0626, 31.2497, 'Cairo, Egypt', false, false, 0, 'embassy_only'::diaspora_centre_state, false),
  ('ke-zw-harare', 'Kenya High Commission Harare', 'high_commission', 'Harare', 'Zimbabwe', 'ZW', 'Africa', 'Southern Africa', -17.8277, 31.0534, 'Harare, Zimbabwe', false, false, 0, 'embassy_only'::diaspora_centre_state, false),
  ('ke-zm-lusaka', 'Kenya High Commission Lusaka', 'high_commission', 'Lusaka', 'Zambia', 'ZM', 'Africa', 'Southern Africa', -15.4166, 28.2833, 'Lusaka, Zambia', false, false, 0, 'embassy_only'::diaspora_centre_state, false),
  ('ke-sd-khartoum', 'Kenya Embassy Khartoum', 'embassy', 'Khartoum', 'Sudan', 'SD', 'Africa', 'East Africa', 15.5007, 32.5599, 'Khartoum, Sudan', false, false, 0, 'embassy_only'::diaspora_centre_state, false),
  ('ke-mw-lilongwe', 'Kenya High Commission Lilongwe', 'high_commission', 'Lilongwe', 'Malawi', 'MW', 'Africa', 'Southern Africa', -13.9626, 33.7741, 'Lilongwe, Malawi', false, false, 0, 'embassy_only'::diaspora_centre_state, false),
  ('ke-so-mogadishu', 'Kenya Embassy Mogadishu', 'embassy', 'Mogadishu', 'Somalia', 'SO', 'Africa', 'East Africa', 2.0469, 45.3182, 'Mogadishu, Somalia', false, false, 0, 'embassy_only'::diaspora_centre_state, false),
  ('ke-ls-maseru', 'Kenya High Commission Maseru', 'high_commission', 'Maseru', 'Lesotho', 'LS', 'Africa', 'Southern Africa', -29.3151, 27.4869, 'Maseru, Lesotho', false, false, 0, 'embassy_only'::diaspora_centre_state, false),
  ('ke-mz-maputo', 'Kenya High Commission Maputo', 'high_commission', 'Maputo', 'Mozambique', 'MZ', 'Africa', 'Southern Africa', -25.9692, 32.5732, 'Maputo, Mozambique', false, false, 0, 'embassy_only'::diaspora_centre_state, false),
  ('ke-cd-kinshasa', 'Kenya Embassy Kinshasa', 'embassy', 'Kinshasa', 'DRC', 'CD', 'Africa', 'Central Africa', -4.3217, 15.3222, 'Kinshasa, DRC', false, false, 0, 'embassy_only'::diaspora_centre_state, false),
  ('ke-gh-accra', 'Kenya High Commission Accra', 'high_commission', 'Accra', 'Ghana', 'GH', 'Africa', 'West Africa', 5.6037, -0.187, 'Accra, Ghana', false, false, 0, 'embassy_only'::diaspora_centre_state, false),
  ('ke-na-windhoek', 'Kenya High Commission Windhoek', 'high_commission', 'Windhoek', 'Namibia', 'NA', 'Africa', 'Southern Africa', -22.5597, 17.0832, 'Windhoek, Namibia', false, false, 0, 'embassy_only'::diaspora_centre_state, false),
  ('ke-ly-tripoli', 'Kenya Embassy Tripoli', 'embassy', 'Tripoli', 'Libya', 'LY', 'Africa', 'North Africa', 32.8872, 13.1913, 'Tripoli, Libya', false, false, 0, 'embassy_only'::diaspora_centre_state, false),
  ('ke-tn-tunis', 'Kenya Embassy Tunis', 'embassy', 'Tunis', 'Tunisia', 'TN', 'Africa', 'North Africa', 36.819, 10.1658, 'Tunis, Tunisia', false, false, 0, 'embassy_only'::diaspora_centre_state, false),
  ('ke-ma-rabat', 'Kenya Embassy Rabat', 'embassy', 'Rabat', 'Morocco', 'MA', 'Africa', 'North Africa', 33.9716, -6.8498, 'Rabat, Morocco', false, false, 0, 'embassy_only'::diaspora_centre_state, false),
  ('ke-dz-algiers', 'Kenya Embassy Algiers', 'embassy', 'Algiers', 'Algeria', 'DZ', 'Africa', 'North Africa', 36.7538, 3.0588, 'Algiers, Algeria', false, false, 0, 'embassy_only'::diaspora_centre_state, false),
  ('ke-mg-antananarivo', 'Kenya Embassy Antananarivo', 'embassy', 'Antananarivo', 'Madagascar', 'MG', 'Africa', 'East Africa', -18.9137, 47.5361, 'Antananarivo, Madagascar', false, false, 0, 'embassy_only'::diaspora_centre_state, false),
  ('ke-dj-djibouti', 'Kenya Embassy Djibouti', 'embassy', 'Djibouti', 'Djibouti', 'DJ', 'Africa', 'East Africa', 11.5892, 43.1456, 'Djibouti City, Djibouti', false, false, 0, 'embassy_only'::diaspora_centre_state, false),
  ('ke-er-asmara', 'Kenya Embassy Asmara', 'embassy', 'Asmara', 'Eritrea', 'ER', 'Africa', 'East Africa', 15.3229, 38.9251, 'Asmara, Eritrea', false, false, 0, 'embassy_only'::diaspora_centre_state, false),
  ('ke-sz-mbabane', 'Kenya High Commission Mbabane', 'high_commission', 'Mbabane', 'Eswatini', 'SZ', 'Africa', 'Southern Africa', -26.3186, 31.141, 'Mbabane, Eswatini', false, false, 0, 'embassy_only'::diaspora_centre_state, false),
  ('ke-us-dc', 'Kenya Embassy Washington DC', 'embassy', 'Washington DC', 'United States', 'US', 'Americas', 'North America', 38.92, -77.0516, '2249 R Street NW, Washington DC 20008', false, true, 1, 'embassy_only'::diaspora_centre_state, false),
  ('ke-us-ny', 'Kenya Consulate New York', 'consulate', 'New York', 'United States', 'US', 'Americas', 'North America', 40.758, -73.9855, '866 United Nations Plaza, New York, NY 10017', false, true, 1, 'embassy_only'::diaspora_centre_state, false),
  ('ke-us-la', 'Kenya Consulate Los Angeles', 'consulate', 'Los Angeles', 'United States', 'US', 'Americas', 'North America', 34.0522, -118.2437, 'Los Angeles, CA', false, true, 1, 'embassy_only'::diaspora_centre_state, false),
  ('ke-ca-ottawa', 'Kenya High Commission Ottawa', 'high_commission', 'Ottawa', 'Canada', 'CA', 'Americas', 'North America', 45.4215, -75.6972, '415 Laurier Avenue East, Ottawa ON K1N 6R4', false, true, 1, 'embassy_only'::diaspora_centre_state, false),
  ('ke-ca-toronto', 'Kenya Consulate Toronto', 'consulate', 'Toronto', 'Canada', 'CA', 'Americas', 'North America', 43.6532, -79.3832, 'Toronto, ON, Canada', false, true, 1, 'embassy_only'::diaspora_centre_state, false),
  ('ke-ca-vancouver', 'Kenya Consulate Vancouver', 'consulate', 'Vancouver', 'Canada', 'CA', 'Americas', 'North America', 49.2827, -123.1207, 'Vancouver, BC, Canada', false, true, 1, 'embassy_only'::diaspora_centre_state, false),
  ('ke-br-brasilia', 'Kenya Embassy Brasilia', 'embassy', 'Brasilia', 'Brazil', 'BR', 'Americas', 'South America', -15.7939, -47.8828, 'Brasilia, Brazil', false, false, 0, 'embassy_only'::diaspora_centre_state, false),
  ('ke-mx-mexicocity', 'Kenya Embassy Mexico City', 'embassy', 'Mexico City', 'Mexico', 'MX', 'Americas', 'North America', 19.4326, -99.1332, 'Mexico City, Mexico', false, false, 0, 'embassy_only'::diaspora_centre_state, false),
  ('ke-gb-london', 'Kenya High Commission London', 'high_commission', 'London', 'United Kingdom', 'GB', 'Europe', 'Western Europe', 51.52, -0.1773, '45 Portland Place, London W1B 1AS', false, true, 1, 'embassy_only'::diaspora_centre_state, false),
  ('ke-de-berlin', 'Kenya Embassy Berlin', 'embassy', 'Berlin', 'Germany', 'DE', 'Europe', 'Western Europe', 52.4961, 13.3206, 'Markgrafenstra\u00dfe 63, 10969 Berlin', false, true, 1, 'embassy_only'::diaspora_centre_state, false),
  ('ke-fr-paris', 'Kenya Embassy Paris', 'embassy', 'Paris', 'France', 'FR', 'Europe', 'Western Europe', 48.8668, 2.306, '3 Rue Cimarosa, 75116 Paris', false, false, 0, 'embassy_only'::diaspora_centre_state, false),
  ('ke-it-rome', 'Kenya Embassy Rome', 'embassy', 'Rome', 'Italy', 'IT', 'Europe', 'Western Europe', 41.9028, 12.4964, 'Via Archimede 164, 00197 Rome', false, false, 0, 'embassy_only'::diaspora_centre_state, false),
  ('ke-be-brussels', 'Kenya Embassy Brussels', 'embassy', 'Brussels', 'Belgium', 'BE', 'Europe', 'Western Europe', 50.8503, 4.3517, 'Avenue Winston Churchill 208, 1180 Brussels', false, false, 0, 'embassy_only'::diaspora_centre_state, false),
  ('ke-se-stockholm', 'Kenya Embassy Stockholm', 'embassy', 'Stockholm', 'Sweden', 'SE', 'Europe', 'Northern Europe', 59.3293, 18.0686, 'Birger Jarlsgatan 37, Stockholm', false, false, 0, 'embassy_only'::diaspora_centre_state, false),
  ('ke-ru-moscow', 'Kenya Embassy Moscow', 'embassy', 'Moscow', 'Russia', 'RU', 'Europe', 'Eastern Europe', 55.7558, 37.6173, 'Moscow, Russia', false, false, 0, 'embassy_only'::diaspora_centre_state, false),
  ('ke-es-madrid', 'Kenya Embassy Madrid', 'embassy', 'Madrid', 'Spain', 'ES', 'Europe', 'Western Europe', 40.4168, -3.7038, 'Madrid, Spain', false, false, 0, 'embassy_only'::diaspora_centre_state, false),
  ('ke-at-vienna', 'Kenya Embassy Vienna', 'embassy', 'Vienna', 'Austria', 'AT', 'Europe', 'Western Europe', 48.2082, 16.3738, 'Vienna, Austria', false, false, 0, 'embassy_only'::diaspora_centre_state, false),
  ('ke-ch-geneva', 'Kenya Consulate Geneva', 'consulate', 'Geneva', 'Switzerland', 'CH', 'Europe', 'Western Europe', 46.2044, 6.1432, 'Geneva, Switzerland', false, false, 0, 'embassy_only'::diaspora_centre_state, false),
  ('ke-gr-athens', 'Kenya Embassy Athens', 'embassy', 'Athens', 'Greece', 'GR', 'Europe', 'Southern Europe', 37.9838, 23.7275, 'Athens, Greece', false, false, 0, 'embassy_only'::diaspora_centre_state, false),
  ('ke-pl-warsaw', 'Kenya Embassy Warsaw', 'embassy', 'Warsaw', 'Poland', 'PL', 'Europe', 'Eastern Europe', 52.2297, 21.0122, 'Warsaw, Poland', false, false, 0, 'embassy_only'::diaspora_centre_state, false),
  ('ke-nl-hague', 'Kenya Embassy The Hague', 'embassy', 'The Hague', 'Netherlands', 'NL', 'Europe', 'Western Europe', 52.0705, 4.3007, 'The Hague, Netherlands', false, false, 0, 'embassy_only'::diaspora_centre_state, false),
  ('ke-ae-abudhabi', 'Kenya Embassy Abu Dhabi', 'embassy', 'Abu Dhabi', 'United Arab Emirates', 'AE', 'MiddleEast', 'Gulf', 24.4539, 54.3773, 'Abu Dhabi, UAE', false, true, 1, 'embassy_only'::diaspora_centre_state, false),
  ('ke-ae-dubai', 'Kenya Consulate Dubai', 'consulate', 'Dubai', 'United Arab Emirates', 'AE', 'MiddleEast', 'Gulf', 25.2048, 55.2708, 'Dubai, UAE', false, true, 1, 'embassy_only'::diaspora_centre_state, false),
  ('ke-qa-doha', 'Kenya Embassy Doha', 'embassy', 'Doha', 'Qatar', 'QA', 'MiddleEast', 'Gulf', 25.2854, 51.531, 'Doha, Qatar', false, true, 1, 'embassy_only'::diaspora_centre_state, false),
  ('ke-sa-riyadh', 'Kenya Embassy Riyadh', 'embassy', 'Riyadh', 'Saudi Arabia', 'SA', 'MiddleEast', 'Gulf', 24.7136, 46.6753, 'Riyadh, Saudi Arabia', false, false, 0, 'embassy_only'::diaspora_centre_state, false),
  ('ke-kw-kuwait', 'Kenya Embassy Kuwait City', 'embassy', 'Kuwait City', 'Kuwait', 'KW', 'MiddleEast', 'Gulf', 29.3759, 47.9774, 'Kuwait City, Kuwait', false, false, 0, 'embassy_only'::diaspora_centre_state, false),
  ('ke-tr-ankara', 'Kenya Embassy Ankara', 'embassy', 'Ankara', 'Turkey', 'TR', 'MiddleEast', 'Levant', 39.9334, 32.8597, 'Ankara, Turkey', false, false, 0, 'embassy_only'::diaspora_centre_state, false),
  ('ke-ir-tehran', 'Kenya Embassy Tehran', 'embassy', 'Tehran', 'Iran', 'IR', 'MiddleEast', 'Levant', 35.6892, 51.389, 'Tehran, Iran', false, false, 0, 'embassy_only'::diaspora_centre_state, false),
  ('ke-il-telaviv', 'Kenya Embassy Tel Aviv', 'embassy', 'Tel Aviv', 'Israel', 'IL', 'MiddleEast', 'Levant', 32.0853, 34.7818, 'Tel Aviv, Israel', false, false, 0, 'embassy_only'::diaspora_centre_state, false),
  ('ke-jp-tokyo', 'Kenya Embassy Tokyo', 'embassy', 'Tokyo', 'Japan', 'JP', 'Asia', 'East Asia', 35.6762, 139.6503, '3-24-3 Yakumo, Meguro-ku, Tokyo', false, false, 0, 'embassy_only'::diaspora_centre_state, false),
  ('ke-cn-beijing', 'Kenya Embassy Beijing', 'embassy', 'Beijing', 'China', 'CN', 'Asia', 'East Asia', 39.9042, 116.4074, 'Sanlitun, Chaoyang District, Beijing', false, false, 0, 'embassy_only'::diaspora_centre_state, false),
  ('ke-in-newdelhi', 'Kenya Embassy New Delhi', 'embassy', 'New Delhi', 'India', 'IN', 'Asia', 'South Asia', 28.5974, 77.2099, 'E-66, Vasant Marg, Vasant Vihar, New Delhi', false, false, 0, 'embassy_only'::diaspora_centre_state, false),
  ('ke-pk-islamabad', 'Kenya High Commission Islamabad', 'high_commission', 'Islamabad', 'Pakistan', 'PK', 'Asia', 'South Asia', 33.7294, 73.0931, 'Islamabad, Pakistan', false, false, 0, 'embassy_only'::diaspora_centre_state, false),
  ('ke-th-bangkok', 'Kenya Embassy Bangkok', 'embassy', 'Bangkok', 'Thailand', 'TH', 'Asia', 'Southeast Asia', 13.7563, 100.5018, 'Bangkok, Thailand', false, false, 0, 'embassy_only'::diaspora_centre_state, false),
  ('ke-kr-seoul', 'Kenya Embassy Seoul', 'embassy', 'Seoul', 'South Korea', 'KR', 'Asia', 'East Asia', 37.5665, 126.978, 'Seoul, South Korea', false, false, 0, 'embassy_only'::diaspora_centre_state, false),
  ('ke-my-kualalumpur', 'Kenya Embassy Kuala Lumpur', 'embassy', 'Kuala Lumpur', 'Malaysia', 'MY', 'Asia', 'Southeast Asia', 3.139, 101.6869, 'Kuala Lumpur, Malaysia', false, false, 0, 'embassy_only'::diaspora_centre_state, false),
  ('ke-au-canberra', 'Kenya High Commission Canberra', 'high_commission', 'Canberra', 'Australia', 'AU', 'Oceania', 'Oceania', -35.2809, 149.13, 'Canberra, ACT, Australia', false, false, 0, 'embassy_only'::diaspora_centre_state, false),
  ('ke-nz-wellington', 'Kenya High Commission Wellington', 'high_commission', 'Wellington', 'New Zealand', 'NZ', 'Oceania', 'Oceania', -41.2865, 174.7762, 'Wellington, New Zealand', false, false, 0, 'embassy_only'::diaspora_centre_state, false)
ON CONFLICT (id) DO UPDATE SET
  mission_name = EXCLUDED.mission_name,
  mission_type = EXCLUDED.mission_type,
  city = EXCLUDED.city,
  country = EXCLUDED.country,
  country_code = EXCLUDED.country_code,
  continent = EXCLUDED.continent,
  region = EXCLUDED.region,
  latitude = EXCLUDED.latitude,
  longitude = EXCLUDED.longitude,
  address = EXCLUDED.address,
  designated_2017 = EXCLUDED.designated_2017,
  designated_2022 = EXCLUDED.designated_2022,
  designation_count = EXCLUDED.designation_count,
  designation_state = EXCLUDED.designation_state,
  is_iebc_confirmed_2027 = EXCLUDED.is_iebc_confirmed_2027,
  updated_at = NOW();
