// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bfatlkobozblunojtltp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJmYXRsa29ib3pibHVub2p0bHRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzgwMTIxNDMsImV4cCI6MjA5MzU4ODE0M30.f4dZkDulvifFELIQn-R7GmXyfltVqJ6AzCIpVoccCdE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});